package com.phoenix.fitpro.domain.model

import java.time.DayOfWeek

/** A full weekly training program created or generated by the AI Coach */
data class TrainingProgram(
    val id: Long = 1,
    val title: String = "Programme Sur-Mesure Ashes",
    val description: String = "Programme équilibré et optimisé par votre Coach IA",
    val goal: FitnessGoal = FitnessGoal.MUSCLE_TONE,
    val days: List<ProgramDay> = emptyList(),
    val coachTips: List<String> = emptyList(),
    val createdAtEpochMs: Long = System.currentTimeMillis()
)

data class ProgramDay(
    val dayOfWeek: DayOfWeek,
    val isRestDay: Boolean = false,
    val title: String,                // e.g. "Push — Pectoraux / Épaules / Triceps" or "Tir à l'arc & Gainage" or "Repos Récupération"
    val sportName: String = "Musculation",
    val sportEmoji: String = "💪",
    val estimatedDurationMin: Int = 45,
    val focusDescription: String = "",
    val exercises: List<ProgramExercise> = emptyList()
)

data class ProgramExercise(
    val name: String,
    val targetSets: Int = 4,
    val targetReps: String = "8-12",
    val restSeconds: Int = 90,
    val notesOrFormTip: String = ""   // e.g. "Garder le dos droit", "Alternative douce pour genoux"
)

/** Preset templates that can be customized */
enum class ProgramTemplate(val labelFr: String, val descriptionFr: String, val emoji: String) {
    CUSTOM_AI("Généré par Coach IA", "Programme 100% calculé selon vos sports, blessures et objectifs", "🧠"),
    PPL("Push / Pull / Legs", "Split classique 3 à 6 jours pour maximiser le développement musculaire", "⚡"),
    UPPER_LOWER("Haut / Bas du corps", "Fréquence 4 jours idéale pour allier force et récupération", "🏋️"),
    FULL_BODY("Full Body (3 jours)", "Entraînement complet du corps 3x par semaine, idéal emploi du temps chargé", "🎯"),
    ARCHERY_ATHLETE("Tir à l'arc & Athlète", "Posture, renforcement haut du dos, stabilité scapulaire et cardio", "🏹")
}
